# Generated by Django 6.0.2 on 2026-02-16 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100, verbose_name='Название сессии')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (минуты)')),
                ('speech_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Темп речи (слов/мин)')),
                ('volume', models.PositiveIntegerField(blank=True, null=True, verbose_name='Громкость (дБ)')),
                ('eye_contact', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зрительный контакт (%)')),
                ('filler_words', models.PositiveIntegerField(blank=True, null=True, verbose_name='Слова-паразиты')),
                ('final_score', models.FloatField(blank=True, null=True, verbose_name='Итоговый балл')),
            ],
        ),
    ]
